"""Add PostLike and PostComment models

Revision ID: 0a3e9bb1065f
Revises: a638ee8b4586
Create Date: 2025-09-06 16:48:16.161275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3e9bb1065f'
down_revision = 'a638ee8b4586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comment_timestamp'), ['timestamp'], unique=False)

    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='_user_post_like_uc')
    )
    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_like_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_like_timestamp'))

    op.drop_table('post_like')
    with op.batch_alter_table('post_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comment_timestamp'))

    op.drop_table('post_comment')
    # ### end Alembic commands ###
