"""Add profile fields to User model

Revision ID: 2ec356dcd01c
Revises: d2b3c4e5f6a7
Create Date: 2025-09-15 18:52:25.800447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec356dcd01c'
down_revision = 'd2b3c4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cover_photo', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_phone_number', ['phone_number'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_phone_number', type_='unique')
        batch_op.drop_column('cover_photo')
        batch_op.drop_column('website')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
