"""Add MutedStory table

Revision ID: 30cc30d9cb4d
Revises: a28b2bcf0eec
Create Date: 2025-10-01 12:18:01.761447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cc30d9cb4d'
down_revision = 'a28b2bcf0eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muted_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muter_id', sa.Integer(), nullable=False),
    sa.Column('muted_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['muted_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['muter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('muter_id', 'muted_id', name='_muter_muted_story_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muted_story')
    # ### end Alembic commands ###
