"""Add duration_hours to Event model

Revision ID: 361099816383
Revises: 77704d208b05
Create Date: 2025-09-18 10:45:44.072457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361099816383'
down_revision = '77704d208b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('duration_hours')

    # ### end Alembic commands ###
