"""Add Department models and relationships

Revision ID: 3c188192c924
Revises: 7598bb02c9d4
Create Date: 2025-09-07 16:58:28.525775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c188192c924'
down_revision = '7598bb02c9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('department_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'department_id')
    )
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_community_department_id_department', 'department', ['department_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_department_id_department', 'department', ['department_id'], ['id'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_project_department_id_department', 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_department_id_department', type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_department_id_department', type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_constraint('fk_community_department_id_department', type_='foreignkey')
        batch_op.drop_column('department_id')

    op.drop_table('department_membership')
    op.drop_table('department')
    # ### end Alembic commands ###
