"""Add read_at to ChatMessage

Revision ID: 3f84d76a1f96
Revises: 5690bd37fca9
Create Date: 2025-09-05 13:52:40.765677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f84d76a1f96'
down_revision = '5690bd37fca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
