"""Add MutedStatusUser model

Revision ID: 43f8486feefd
Revises: 99b4e26159da
Create Date: 2025-09-05 19:26:20.904827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f8486feefd'
down_revision = '99b4e26159da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muted_status_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muter_id', sa.Integer(), nullable=False),
    sa.Column('muted_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['muted_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['muter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('muter_id', 'muted_id', name='_muter_muted_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muted_status_user')
    # ### end Alembic commands ###
