"""Add Bookmark model

Revision ID: 74246ce89223
Revises: 87dda1a241b5
Create Date: 2025-09-13 13:28:24.456442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74246ce89223'
down_revision = '87dda1a241b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.create_index('ix_bookmark_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmark_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_timestamp'))
        batch_op.drop_index('ix_bookmark_target')

    op.drop_table('bookmark')
    # ### end Alembic commands ###
