"""Add community_id to Post model

Revision ID: 7598bb02c9d4
Revises: e30af1858941
Create Date: 2025-09-06 17:44:09.257338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7598bb02c9d4'
down_revision = 'e30af1858941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_community_id', 'community', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_community_id', type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###
