"""Add theme and chat_wallpaper to User model

Revision ID: 7d0b0a004546
Revises: 8bb223421731
Create Date: 2025-09-05 16:51:03.769215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0b0a004546'
down_revision = '8bb223421731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('chat_wallpaper', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('chat_wallpaper')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
