"""Add sub_category to CreativeWork

Revision ID: 81e06020c2f7
Revises: 74246ce89223
Create Date: 2025-09-13 13:33:35.140838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e06020c2f7'
down_revision = '74246ce89223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.drop_column('sub_category')

    # ### end Alembic commands ###
