"""Add Challenge and ChallengeSubmission models

Revision ID: 87dda1a241b5
Revises: a4b0adfe1385
Create Date: 2025-09-13 12:27:30.243093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dda1a241b5'
down_revision = 'a4b0adfe1385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('prize', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_timestamp'), ['timestamp'], unique=False)

    op.create_table('challenge_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('submission_type', sa.String(length=50), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenge_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_submission_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_submission_timestamp'))

    op.drop_table('challenge_submission')
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_timestamp'))

    op.drop_table('challenge')
    # ### end Alembic commands ###
