"""Add Vote model for challenge submissions

Revision ID: 88c0170a3ced
Revises: 9bc4f19f2a6d
Create Date: 2025-09-13 14:11:34.839060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c0170a3ced'
down_revision = '9bc4f19f2a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['challenge_submission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_timestamp'))

    op.drop_table('vote')
    # ### end Alembic commands ###
