"""Add forwarding info to ChatMessage

Revision ID: 8bb223421731
Revises: 902b4a95bfad
Create Date: 2025-09-05 14:09:21.111352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb223421731'
down_revision = '902b4a95bfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_forwarded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('forwarded_from_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chat_message_forwarded_from_id_user', 'user', ['forwarded_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_message_forwarded_from_id_user', type_='foreignkey')
        batch_op.drop_column('forwarded_from_id')
        batch_op.drop_column('is_forwarded')

    # ### end Alembic commands ###
