"""Add profile fields to User model

Revision ID: 8e38369e5706
Revises: d2b3c4e5f6a7
Create Date: 2025-09-15 18:39:45.919653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e38369e5706'
down_revision = 'd2b3c4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_subscription_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proof_of_payment_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('banned_from_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banned_by_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='_community_user_ban_uc')
    )
    op.create_table('community_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('daily_posts', sa.Integer(), nullable=True),
    sa.Column('daily_comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'date', name='_community_date_uc')
    )
    with op.batch_alter_table('community_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_analytics_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_analytics_date'), ['date'], unique=False)

    op.create_table('muted_in_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('muted_by_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['muted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='_community_user_mute_uc')
    )
    op.create_table('pinned_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('post_impression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_impression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_impression_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_impression_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_impression_viewer_id'), ['viewer_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('scheduled_for', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_boosted', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key('fk_post_page_id', 'user_page', ['page_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('premium_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cover_photo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('profile_banner_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_theme', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bio_links', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint('uq_user_phone_number', ['phone_number'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    with op.batch_alter_table('user_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_banner_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('action_button_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('action_button_type')
        batch_op.drop_column('website')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('cover_banner_url')
        batch_op.drop_column('profile_pic_url')
        batch_op.drop_column('category')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('bio_links')
        batch_op.drop_column('profile_theme')
        batch_op.drop_column('profile_banner_url')
        batch_op.drop_column('cover_photo')
        batch_op.drop_column('premium_expires_at')
        batch_op.drop_column('website')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('username')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_boosted')
        batch_op.drop_column('scheduled_for')
        batch_op.drop_column('post_status')
        batch_op.drop_column('page_id')

    with op.batch_alter_table('post_impression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_impression_viewer_id'))
        batch_op.drop_index(batch_op.f('ix_post_impression_timestamp'))
        batch_op.drop_index(batch_op.f('ix_post_impression_post_id'))

    op.drop_table('post_impression')
    op.drop_table('pinned_post')
    op.drop_table('muted_in_community')
    with op.batch_alter_table('community_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_analytics_date'))
        batch_op.drop_index(batch_op.f('ix_community_analytics_community_id'))

    op.drop_table('community_analytics')
    op.drop_table('banned_from_community')
    op.drop_table('referral')
    op.drop_table('premium_subscription_request')
    op.drop_table('feedback')
    # ### end Alembic commands ###
