"""Add last_seen to User model

Revision ID: 902b4a95bfad
Revises: 3f84d76a1f96
Create Date: 2025-09-05 13:58:58.446209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902b4a95bfad'
down_revision = '3f84d76a1f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
