"""Add sharing functionality to Post model

Revision ID: 932bd4ae6f43
Revises: b7ece1f602f1
Create Date: 2025-09-12 15:10:41.426429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932bd4ae6f43'
down_revision = 'b7ece1f602f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_post_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key('fk_post_original_post_id', 'post', ['original_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_original_post_id', type_='foreignkey')
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('original_post_id')

    # ### end Alembic commands ###
