"""Add notification settings to User model

Revision ID: 94a839541546
Revises: 75e75619d522
Create Date: 2025-09-05 17:19:52.671490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a839541546'
down_revision = '75e75619d522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('group_notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('group_notifications_enabled')
        batch_op.drop_column('message_notifications_enabled')

    # ### end Alembic commands ###
