"""Add tags to CreativeWork and Reel

Revision ID: 952f7693f71c
Revises: 81e06020c2f7
Create Date: 2025-09-13 13:57:13.897956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952f7693f71c'
down_revision = '81e06020c2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
