"""Add phone_number_verified to User model

Revision ID: 969b243a2790
Revises: 2ec356dcd01c
Create Date: 2025-09-15 19:25:04.599218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969b243a2790'
down_revision = '2ec356dcd01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number_verified')

    # ### end Alembic commands ###
