"""Enhance Status and Poll models for status features

Revision ID: 99b4e26159da
Revises: 94a839541546
Create Date: 2025-09-05 18:34:05.073839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b4e26159da'
down_revision = '94a839541546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_poll_status_id_status'), 'status', ['status_id'], ['id'])

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_column('background')

    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_poll_status_id_status'), type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
