"""Add shared item fields to Post model

Revision ID: 9bc4f19f2a6d
Revises: 952f7693f71c
Create Date: 2025-09-13 14:04:26.849243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc4f19f2a6d'
down_revision = '952f7693f71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_creative_work_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shared_reel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_shared_reel', 'reel', ['shared_reel_id'], ['id'])
        batch_op.create_foreign_key('fk_post_shared_creative_work', 'creative_work', ['shared_creative_work_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_shared_reel', type_='foreignkey')
        batch_op.drop_constraint('fk_post_shared_creative_work', type_='foreignkey')
        batch_op.drop_column('shared_reel_id')
        batch_op.drop_column('shared_creative_work_id')

    # ### end Alembic commands ###
