"""Add default_post_privacy to User model

Revision ID: a1300b7c443e
Revises: 969b243a2790
Create Date: 2025-09-15 19:49:12.991682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1300b7c443e'
down_revision = '969b243a2790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_post_privacy', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('default_post_privacy')

    # ### end Alembic commands ###
