"""Add due_date to Assignment model

Revision ID: a28b2bcf0eec
Revises: 32fdfa9fffc7
Create Date: 2025-09-21 13:50:04.236808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28b2bcf0eec'
down_revision = '32fdfa9fffc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
