"""Add genre and cover_image_url to CreativeWork

Revision ID: a4b0adfe1385
Revises: f637cd984f00
Create Date: 2025-09-13 12:23:57.865716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b0adfe1385'
down_revision = 'f637cd984f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
