"""Add privacy settings to User model

Revision ID: a6a688670660
Revises: 43f8486feefd
Create Date: 2025-09-05 19:58:37.641240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a688670660'
down_revision = '43f8486feefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_last_seen', sa.String(length=50), nullable=False, server_default='everyone'))
        batch_op.add_column(sa.Column('privacy_profile_pic', sa.String(length=50), nullable=False, server_default='everyone'))
        batch_op.add_column(sa.Column('privacy_about', sa.String(length=50), nullable=False, server_default='everyone'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('privacy_about')
        batch_op.drop_column('privacy_profile_pic')
        batch_op.drop_column('privacy_last_seen')

    # ### end Alembic commands ###
