"""Add reaction_type to Like model

Revision ID: b7ece1f602f1
Revises: 7598bb02c9d4
Create Date: 2025-09-12 15:06:47.593219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ece1f602f1'
down_revision = '7598bb02c9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reaction_type', sa.String(length=20), server_default='like', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_column('reaction_type')

    # ### end Alembic commands ###
