"""Add permission flags to User model

Revision ID: b8f025fbf113
Revises: cb0fb2c5a8d8
Create Date: 2025-09-05 08:44:13.766960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f025fbf113'
down_revision = 'cb0fb2c5a8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_send_messages', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('can_make_calls', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_make_calls')
        batch_op.drop_column('can_send_messages')

    # ### end Alembic commands ###
