"""Add creativity hub models

Revision ID: c1a2b3d4e5f6
Revises: e30af1858941
Create Date: 2025-09-13 14:44:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a2b3d4e5f6'
down_revision = '932bd4ae6f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='_user_target_bookmark_uc')
    )
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.create_index('ix_bookmark_target', ['target_type', 'target_id'], unique=False)

    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('style_options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.create_table('challenge_submissions',
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('creative_work_id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['creative_work_id'], ['creative_work.id'], ),
    sa.PrimaryKeyConstraint('challenge_id', 'creative_work_id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['creative_work.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', 'submission_id', name='_user_challenge_submission_vote_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('challenge_submissions')
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('tags')
        batch_op.drop_column('style_options')
        batch_op.drop_column('genre')
        batch_op.drop_column('sub_category')

    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_index('ix_bookmark_target')

    op.drop_table('bookmark')
    op.drop_table('challenge')
    # ### end Alembic commands ###
