"""Modify CallHistory for group calls

Revision ID: cb0fb2c5a8d8
Revises: de01f562ae46
Create Date: 2025-09-05 07:44:10.719766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0fb2c5a8d8'
down_revision = 'de01f562ae46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('callee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_call_history_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_history_is_active'))
        batch_op.alter_column('callee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
