"""Add privacy to Post model

Revision ID: db6ddbba5f9a
Revises: 813ab566fdd5
Create Date: 2025-09-06 10:30:59.672641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6ddbba5f9a'
down_revision = '813ab566fdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('privacy')

    # ### end Alembic commands ###
