"""Refactor likes and comments to be polymorphic

Revision ID: e30af1858941
Revises: a638ee8b4586
Create Date: 2025-09-06 17:41:20.360141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30af1858941'
down_revision = 'a638ee8b4586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generic_comment', schema=None) as batch_op:
        batch_op.create_index('ix_comment_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generic_comment_timestamp'), ['timestamp'], unique=False)

    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index('ix_like_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_like_timestamp'), ['timestamp'], unique=False)

    op.create_table('course_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_comment_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_timestamp'))

    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('course_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_comment_timestamp'))

    op.drop_table('course_comment')
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_like_timestamp'))
        batch_op.drop_index('ix_like_target')

    op.drop_table('like')
    with op.batch_alter_table('generic_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generic_comment_timestamp'))
        batch_op.drop_index('ix_comment_target')

    op.drop_table('generic_comment')
    # ### end Alembic commands ###
