"""Add status reply to ChatMessage model

Revision ID: f1e473311f90
Revises: a6a688670660
Create Date: 2025-09-05 20:13:26.564547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e473311f90'
down_revision = 'a6a688670660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replied_to_status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_chatmessage_replied_to_status_id_status'), 'status', ['replied_to_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chatmessage_replied_to_status_id_status'), type_='foreignkey')
        batch_op.drop_column('replied_to_status_id')

    # ### end Alembic commands ###
