"""Add style_options to CreativeWork and make media_url nullable

Revision ID: f637cd984f00
Revises: 932bd4ae6f43
Create Date: 2025-09-13 12:22:15.150141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f637cd984f00'
down_revision = '932bd4ae6f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_options', sa.JSON(), nullable=True))
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_work', schema=None) as batch_op:
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('style_options')

    # ### end Alembic commands ###
